Expose named export (fix TypeScript>=1.8 with native ESM)
fastify/fluent-json-schema pull request #207
Opened 2023-01-31 15:49 UTC by greguz

#### Checklist

- [x] run `npm run test`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-01-31 16:13 UTC, Fdawgs requested changes

2023-01-31 16:13 UTC, Fdawgs commented on README.md
> +A named export is also aviable to work with native ESM modules (aka `Node16` or `NodeNext`):
```suggestion
A named export is also available to work with native ESM modules:
```

2023-01-31 16:38 UTC, Uzlopak commented
@climba03003 
;/

2023-01-31 16:38 UTC, mcollina approved these changes
lgtm

2023-01-31 17:01 UTC, climba03003 reviewed
I wouldn't block for a named export with shorten name.

2023-01-31 17:06 UTC, greguz commented on src/FluentJSONSchema.js
> +exports.S = fluentSchema
You're right.

2023-02-03 06:59 UTC, Inviz commented
Is this a real life? i will finally be able to update TS? LGTM

2023-02-05 23:53 UTC, mcollina commented
@Fdawgs @aboutlo PTAL

2023-02-06 04:41 UTC, Fdawgs approved these changes

2023-02-07 14:23 UTC, greguz commented
I've noticed a couple of things:
- The `Prettier` badge is wrong, I see this repo uses `Standard` for linting. May I update the badge?
- There's no `files` field inside the `package.json`, so all test files (and much more) are packaged and shipped to `NPM`. May add this field?

Also I've just created a pure-ESM version of this project under the name [fluent-json-schema-es](https://www.npmjs.com/package/fluent-json-schema-es) where you can use the `import S from 'fluent-json-schema-es` syntax freely.

By doing that I saw that a double-module package (bot ESM and CJS code inside the same package) could potentially fix the issue with TypeScript entirely. I suggest [`rollup`](https://rollupjs.org/) to do che ESM>CJS conversion.

What are your thoughts about It? I will be happy to make this change and deprecate `fluent-json-schema-es`.

2023-02-07 14:26 UTC, Fdawgs commented
>     * The `Prettier` badge is wrong, I see this repo uses `Standard` for linting. May I update the badge?

Sure, please open a separate PR. 😄 

>     * There's no `files` field inside the `package.json`, so all test files (and much more) are packaged and shipped to `NPM`. May add this field?

See https://github.com/fastify/skeleton/issues/42



> Also I've just created a pure-ESM version of this project under the name [fluent-json-schema-es](https://www.npmjs.com/package/fluent-json-schema-es) where you can use the `import S from 'fluent-json-schema-es` syntax freely.
> 
> By doing that I saw that a double-module package (bot ESM and CJS code inside the same package) could potentially fix the issue with TypeScript entirely. I suggest [`rollup`](https://rollupjs.org/) to do che ESM>CJS conversion.
> 
> What are your thoughts about It? I will be happy to make this change and deprecate `fluent-json-schema-es`.

See https://github.com/fastify/fastify/issues/2847 for ESM discussion.

2023-02-13 22:18 UTC, merged

2023-02-22 06:16 UTC, Inviz commented
when's release?