Update for Fastify v5
fastify/fluent-json-schema pull request #242
Opened 2024-04-15 18:37 UTC by gurgunday

2024-04-18 18:42 UTC, Fdawgs approved these changes

2024-04-19 09:43 UTC, mcollina requested changes
This is a module, not a plugin. I don't think it needs this update

2024-04-19 10:18 UTC, gurgunday commented
Just updated the workflow slightly to match other library ones

2024-04-22 12:42 UTC, mcollina approved these changes
lgtm

2024-04-22 12:43 UTC, merged